In [20]:
import fastf1 as f1
import pandas as pd

In [21]:
# Import weekend data from FastF1
YEAR = 2025
GP = 18

gp = f1.get_event(YEAR, GP)

if gp.EventFormat == 'conventional':
    fp1 = gp.get_session('Practice 1')
    fp1.load()
    fp2 = gp.get_session('Practice 2')
    fp2.load()
    fp3 = gp.get_session('Practice 3')
    fp3.load()
    ss = None
    sprint = None
    qualy = gp.get_session('Qualifying')
    qualy.load()
    race = gp.get_session('Race')
    race.load()
else:
    fp1 = gp.get_session('Practice 1')
    fp1.load()
    fp2 = None
    fp3 = None
    ss = gp.get_session('Sprint Shootout')
    ss.load()
    sprint = gp.get_session('Sprint')
    sprint.load()
    qualy = gp.get_session('Qualifying')
    qualy.load()
    race = gp.get_session('Race')
    race.load()

Request for URL https://raw.githubusercontent.com/theOehrly/f1schedule/master/schedule_2025.json failed; using cached response
Traceback (most recent call last):
  File "c:\Users\pau.peirats\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\pau.peirats\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "c:\Users\pau.peirats\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 571, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\pau.peirats\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1395, in getresponse
    response.begin()
  File "c:\Users\pau.peirats\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 325, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\pau.peirats\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 294, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\pau.peirats\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\adapters.py", line 644, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\pau.peirats\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "c:\Users\pau.peirats\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\retry.py", line 490, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\pau.peirats\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "c:\Users\pau.peirats\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\pau.peirats\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "c:\Users\pau.peirats\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 571, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\pau.peirats\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1395, in getresponse
    response.begin()
  File "c:\Users\pau.peirats\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 325, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\pau.peirats\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 294, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\pau.peirats\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests_cache\session.py", line 292, in _resend
    response = self._send_and_cache(request, actions, cached_response, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\pau.peirats\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests_cache\session.py", line 260, in _send_and_cache
    response = super().send(request, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\pau.peirats\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastf1\req.py", line 112, in send
    return super().send(request, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\pau.peirats\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\pau.peirats\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\adapters.py", line 659, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
core           INFO 	Loading data for Singapore Grand Prix - Practice 1 [v3.8.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '5', '6', '10', '12', '14', '16', '18', '22', '23', '27', '30', '31', '43', '44', '55', '63', '81', '87']
core           INFO 	Loading data for Singapore Grand Prix - Practice 2 [v3.8.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '5', '6', '10', '12', '14', '16', '18', '22', '23', '27', '30', '31', '43', '44', '55', '63', '81', '87']
core           INFO 	Loading data for Singapore Grand Prix - Practice 3 [v3.8.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '5', '6', '10', '12', '14', '16', '18', '22', '23', '27', '30', '31', '43', '44', '55', '63', '81', '87']
core           INFO 	Loading data for Singapore Grand Prix - Qualifying [v3.8.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['63', '1', '81', '12', '4', '44', '16', '6', '87', '14', '27', '30', '22', '5', '18', '43', '31', '10', '23', '55']
core           INFO 	Loading data for Singapore Grand Prix - Race [v3.8.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['63', '1', '4', '81', '12', '16', '14', '44', '87', '55', '6', '22', '18', '23', '30', '43', '5', '31', '10', '27']

In [25]:
# Convert session results to DataFrames
qualy_res = qualy.results
qualy_res.head()

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Laps
63,63,G RUSSELL,RUS,russell,Mercedes,00D7B6,mercedes,George,Russell,George Russell,...,1.0,,NaN,0 days 00:01:29.928000,0 days 00:01:29.562000,0 days 00:01:29.158000,NaT,,NaN,NaN
1,1,M VERSTAPPEN,VER,max_verstappen,Red Bull Racing,4781D7,red_bull,Max,Verstappen,Max Verstappen,...,2.0,,NaN,0 days 00:01:30.028000,0 days 00:01:29.572000,0 days 00:01:29.340000,NaT,,NaN,NaN
81,81,O PIASTRI,PIA,piastri,McLaren,F47600,mclaren,Oscar,Piastri,Oscar Piastri,...,3.0,,NaN,0 days 00:01:30.313000,0 days 00:01:29.813000,0 days 00:01:29.524000,NaT,,NaN,NaN
12,12,K ANTONELLI,ANT,antonelli,Mercedes,00D7B6,mercedes,Kimi,Antonelli,Kimi Antonelli,...,4.0,,NaN,0 days 00:01:30.036000,0 days 00:01:29.649000,0 days 00:01:29.537000,NaT,,NaN,NaN
4,4,L NORRIS,NOR,norris,McLaren,F47600,mclaren,Lando,Norris,Lando Norris,...,5.0,,NaN,0 days 00:01:29.932000,0 days 00:01:29.809000,0 days 00:01:29.586000,NaT,,NaN,NaN

In [26]:
# Clean the results DataFrame as needed
qualy_res.drop(columns=['BroadcastName', 'DriverId', 'TeamColor', 'TeamId', 'FirstName', 'LastName', 'HeadshotUrl', 'CountryCode'], inplace=True)

In [27]:
qualy_res.head()

,DriverNumber,Abbreviation,TeamName,FullName,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Laps
63,63,RUS,Mercedes,George Russell,1.0,,NaN,0 days 00:01:29.928000,0 days 00:01:29.562000,0 days 00:01:29.158000,NaT,,NaN,NaN
1,1,VER,Red Bull Racing,Max Verstappen,2.0,,NaN,0 days 00:01:30.028000,0 days 00:01:29.572000,0 days 00:01:29.340000,NaT,,NaN,NaN
81,81,PIA,McLaren,Oscar Piastri,3.0,,NaN,0 days 00:01:30.313000,0 days 00:01:29.813000,0 days 00:01:29.524000,NaT,,NaN,NaN
12,12,ANT,Mercedes,Kimi Antonelli,4.0,,NaN,0 days 00:01:30.036000,0 days 00:01:29.649000,0 days 00:01:29.537000,NaT,,NaN,NaN
4,4,NOR,McLaren,Lando Norris,5.0,,NaN,0 days 00:01:29.932000,0 days 00:01:29.809000,0 days 00:01:29.586000,NaT,,NaN,NaN

In [28]:
# Convert session results to DataFrames
race_res = race.results
race_res.head()

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Laps
63,63,G RUSSELL,RUS,russell,Mercedes,00D7B6,mercedes,George,Russell,George Russell,...,1.0,1,1.0,NaT,NaT,NaT,0 days 01:40:22.367000,Finished,25.0,62.0
1,1,M VERSTAPPEN,VER,max_verstappen,Red Bull Racing,4781D7,red_bull,Max,Verstappen,Max Verstappen,...,2.0,2,2.0,NaT,NaT,NaT,0 days 00:00:05.430000,Finished,18.0,62.0
4,4,L NORRIS,NOR,norris,McLaren,F47600,mclaren,Lando,Norris,Lando Norris,...,3.0,3,5.0,NaT,NaT,NaT,0 days 00:00:06.066000,Finished,15.0,62.0
81,81,O PIASTRI,PIA,piastri,McLaren,F47600,mclaren,Oscar,Piastri,Oscar Piastri,...,4.0,4,3.0,NaT,NaT,NaT,0 days 00:00:08.146000,Finished,12.0,62.0
12,12,K ANTONELLI,ANT,antonelli,Mercedes,00D7B6,mercedes,Kimi,Antonelli,Kimi Antonelli,...,5.0,5,4.0,NaT,NaT,NaT,0 days 00:00:33.681000,Finished,10.0,62.0

In [29]:
# Clean the results DataFrame as needed
race_res.drop(columns=['BroadcastName', 'DriverId', 'TeamColor', 'TeamId', 'FirstName', 'LastName', 'HeadshotUrl', 'CountryCode'], inplace=True)

In [31]:
race_res

,DriverNumber,Abbreviation,TeamName,FullName,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Laps
63,63,RUS,Mercedes,George Russell,1.0,1,1.0,NaT,NaT,NaT,0 days 01:40:22.367000,Finished,25.0,62.0
1,1,VER,Red Bull Racing,Max Verstappen,2.0,2,2.0,NaT,NaT,NaT,0 days 00:00:05.430000,Finished,18.0,62.0
4,4,NOR,McLaren,Lando Norris,3.0,3,5.0,NaT,NaT,NaT,0 days 00:00:06.066000,Finished,15.0,62.0
81,81,PIA,McLaren,Oscar Piastri,4.0,4,3.0,NaT,NaT,NaT,0 days 00:00:08.146000,Finished,12.0,62.0
12,12,ANT,Mercedes,Kimi Antonelli,5.0,5,4.0,NaT,NaT,NaT,0 days 00:00:33.681000,Finished,10.0,62.0
16,16,LEC,Ferrari,Charles Leclerc,6.0,6,7.0,NaT,NaT,NaT,0 days 00:00:45.996000,Finished,8.0,62.0
14,14,ALO,Aston Martin,Fernando Alonso,7.0,7,10.0,NaT,NaT,NaT,0 days 00:01:20.667000,Finished,6.0,62.0
44,44,HAM,Ferrari,Lewis Hamilton,8.0,8,6.0,NaT,NaT,NaT,0 days 00:01:25.251000,Finished,4.0,62.0
87,87,BEA,Haas F1 Team,Oliver Bearman,9.0,9,9.0,NaT,NaT,NaT,0 days 00:01:33.527000,Finished,2.0,62.0
55,55,SAI,Williams,Carlos Sainz,10.0,10,18.0,NaT,NaT,NaT,0 days 00:00:10.754000,Lapped,1.0,61.0
6,6,HAD,Racing Bulls,Isack Hadjar,11.0,11,8.0,NaT,NaT,NaT,0 days 00:00:17.335000,Lapped,0.0,61.0
22,22,TSU,Red Bull Racing,Yuki Tsunoda,12.0,12,13.0,NaT,NaT,NaT,0 days 00:00:19.269000,Lapped,0.0,61.0
18,18,STR,Aston Martin,Lance Stroll,13.0,13,15.0,NaT,NaT,NaT,0 days 00:00:24.490000,Lapped,0.0,61.0
23,23,ALB,Williams,Alexander Albon,14.0,14,20.0,NaT,NaT,NaT,0 days 00:00:25.320000,Lapped,0.0,61.0
30,30,LAW,Racing Bulls,Liam Lawson,15.0,15,12.0,NaT,NaT,NaT,0 days 00:00:27.145000,Lapped,0.0,61.0
43,43,COL,Alpine,Franco Colapinto,16.0,16,16.0,NaT,NaT,NaT,0 days 00:00:42.890000,Lapped,0.0,61.0
5,5,BOR,Kick Sauber,Gabriel Bortoleto,17.0,17,14.0,NaT,NaT,NaT,0 days 00:00:46.753000,Lapped,0.0,61.0
31,31,OCO,Haas F1 Team,Esteban Ocon,18.0,18,17.0,NaT,NaT,NaT,0 days 00:00:47.133000,Lapped,0.0,61.0
10,10,GAS,Alpine,Pierre Gasly,19.0,19,19.0,NaT,NaT,NaT,0 days 00:00:47.461000,Lapped,0.0,61.0
27,27,HUL,Kick Sauber,Nico Hulkenberg,20.0,20,11.0,NaT,NaT,NaT,0 days 00:00:49.040000,Lapped,0.0,61.0